import { Transaction } from './transaction.model';

export const mockTransactions: Transaction[] = [
  {
    id: 'tx_001',
    date: '2025-06-01',
    amount: 99.99,
    status: 'successful',
    description: 'Monthly Premium Subscription',
    category: 'Subscription',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_002',
    date: '2025-05-28',
    amount: 299.99,
    status: 'successful',
    description: 'Annual Team License',
    category: 'License',
    paymentMethod: 'PayPal',
  },
  {
    id: 'tx_003',
    date: '2025-05-25',
    amount: 49.99,
    status: 'failed',
    description: 'Add-on Package Purchase',
    category: 'Add-ons',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_004',
    date: '2025-05-20',
    amount: 149.99,
    status: 'successful',
    description: 'Consulting Services',
    category: 'Services',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'tx_005',
    date: '2025-05-15',
    amount: 75.0,
    status: 'pending',
    description: 'Support Package',
    category: 'Support',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_006',
    date: '2025-05-10',
    amount: 199.99,
    status: 'successful',
    description: 'Developer Tools Bundle',
    category: 'Software',
    paymentMethod: 'PayPal',
  },
  {
    id: 'tx_007',
    date: '2025-05-05',
    amount: 29.99,
    status: 'successful',
    description: 'Cloud Storage Upgrade',
    category: 'Storage',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_008',
    date: '2025-05-01',
    amount: 399.99,
    status: 'failed',
    description: 'Enterprise License',
    category: 'License',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'tx_009',
    date: '2025-04-28',
    amount: 89.99,
    status: 'successful',
    description: 'Security Package',
    category: 'Security',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_010',
    date: '2025-04-25',
    amount: 159.99,
    status: 'pending',
    description: 'API Access',
    category: 'API',
    paymentMethod: 'PayPal',
  },
  {
    id: 'tx_011',
    date: '2025-04-20',
    amount: 49.99,
    status: 'successful',
    description: 'Mobile App Subscription',
    category: 'Subscription',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_012',
    date: '2025-04-15',
    amount: 249.99,
    status: 'successful',
    description: 'Custom Integration',
    category: 'Services',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'tx_013',
    date: '2025-04-10',
    amount: 19.99,
    status: 'failed',
    description: 'Email Templates',
    category: 'Add-ons',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_014',
    date: '2025-04-05',
    amount: 599.99,
    status: 'successful',
    description: 'Annual Enterprise Plan',
    category: 'Subscription',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'tx_015',
    date: '2025-04-01',
    amount: 79.99,
    status: 'successful',
    description: 'Analytics Package',
    category: 'Add-ons',
    paymentMethod: 'PayPal',
  },
  {
    id: 'tx_016',
    date: '2025-03-28',
    amount: 129.99,
    status: 'pending',
    description: 'Training Session',
    category: 'Services',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_017',
    date: '2025-03-25',
    amount: 349.99,
    status: 'successful',
    description: 'Database Migration',
    category: 'Services',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'tx_018',
    date: '2025-03-20',
    amount: 39.99,
    status: 'successful',
    description: 'SSL Certificate',
    category: 'Security',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'tx_019',
    date: '2025-03-15',
    amount: 89.99,
    status: 'failed',
    description: 'Custom Domain',
    category: 'Domain',
    paymentMethod: 'PayPal',
  },
  {
    id: 'tx_020',
    date: '2025-03-10',
    amount: 199.99,
    status: 'successful',
    description: 'Consulting Hours',
    category: 'Services',
    paymentMethod: 'Bank Transfer',
  },
];
